package Proyecto;
import javax.swing.*;
import java.io.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ingiv
 * 
 *          EQUIPO 15
 * 
 *      Iván Martínez Aguirre
 *      Enrique Juárez Mendoza
 * 
 *      INSTRUCCIONES A IDENTIFICAR:
 * 
 *  AAM 	CMPSB 	POPF 	STI 	INT 	NOT 	
 *  
 *  AND 	CMP 	JG 	JNB 	JNLE 	JA
 * 
 * 
 */

public class VentanaArchivo extends javax.swing.JFrame {
    GestionA gestion = new GestionA();  public static int i=0,k=0;
    String aux=null,aux1=null;
    
    public VentanaArchivo(){
    initComponents();
    BotonRegresa.setEnabled(false);
    BotonSepara.setEnabled(false);
    }
        
    public VentanaArchivo(String ruta) {
    initComponents();
    aux=ruta;
    BotonSepara.setEnabled(false);
    botonIdenCorrecto.setEnabled(false);
    botonIdentifica.setEnabled(false);
    botonTabla.setEnabled(false);
    }
      
    //Desbloquear botones 
    public void habilitarBoton(){
    if(aux!=null){
    BotonSepara.setEnabled(true);
    botonIdenCorrecto.setEnabled(true);
    botonIdentifica.setEnabled(true);
    botonTabla.setEnabled(true);
    BotonI.setEnabled(false);
    }
    }
    
    //Mostrar todos los datos del archivo original   
    public void mostrarDatosDeTabla(){
    File archivo=null;
    FileReader FileR=null;
    BufferedReader Buffered=null;
        try {
            archivo=new File(aux);
            FileR=new FileReader(archivo);
            Buffered=new BufferedReader(FileR);
            String informacion;
            DefaultTableModel tabla=new DefaultTableModel();
            tabla.addColumn("Datos del Archivo");
               while((informacion=Buffered.readLine())!=null){      
               if(!informacion.equals("")){
               tabla.addRow(new String[]{informacion});
               }
            }
            this.jTextArea1.setModel(tabla); 
        } catch (Exception e) {
        }finally{
       try{
           if(null!=FileR) FileR.close();
       }catch(IOException e2){} 
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonRegresa = new javax.swing.JButton();
        BotonSepara = new javax.swing.JButton();
        BotonI = new javax.swing.JButton();
        botonIdentifica = new javax.swing.JButton();
        botonIdenCorrecto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTable();
        botonTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Archivo Principal");

        BotonRegresa.setText("Regresar");
        BotonRegresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresaActionPerformed(evt);
            }
        });

        BotonSepara.setText("Separar Elementos");
        BotonSepara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeparaActionPerformed(evt);
            }
        });

        BotonI.setText("Iniciar");
        BotonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIActionPerformed(evt);
            }
        });

        botonIdentifica.setText("Identificar Elementos Separados");
        botonIdentifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIdentificaActionPerformed(evt);
            }
        });

        botonIdenCorrecto.setText("Identificar Elementos Correctos");
        botonIdenCorrecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIdenCorrectoActionPerformed(evt);
            }
        });

        jTextArea1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTextArea1);

        botonTabla.setText("Tabla de Simbolos");
        botonTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BotonRegresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonSepara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIdentifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIdenCorrecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegresa)
                    .addComponent(BotonSepara)
                    .addComponent(BotonI)
                    .addComponent(botonIdenCorrecto)
                    .addComponent(botonIdentifica)
                    .addComponent(botonTabla))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIActionPerformed
       if(aux!=null){
       mostrarDatosDeTabla();
       habilitarBoton();
       }else{
       JOptionPane.showMessageDialog(null, "Archivo vacío");
       } 
    }//GEN-LAST:event_BotonIActionPerformed

    private void BotonRegresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresaActionPerformed
    VentanaPrincipal ven = new VentanaPrincipal();
    ven.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BotonRegresaActionPerformed

    private void BotonSeparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeparaActionPerformed
    if(aux!=null){
       VentanaSepara ven = new VentanaSepara(aux);
       ven.setVisible(true);
       aux1=ven.getAux2();
       }else{
       JOptionPane.showMessageDialog(null, "Archivo vacío");
       }             
    }//GEN-LAST:event_BotonSeparaActionPerformed
    
    private void botonIdentificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIdentificaActionPerformed
    if(aux1!=null){
       VentanaIdentificacion ven = new VentanaIdentificacion(aux1);
       ven.setVisible(true);
       }else{
       JOptionPane.showMessageDialog(null, "Primero separe los elementos del archivo");
       }        
    }//GEN-LAST:event_botonIdentificaActionPerformed

    private void botonIdenCorrectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIdenCorrectoActionPerformed
    if(aux!=null){
        VentanaSegmento ven = new VentanaSegmento(aux);
       ven.setVisible(true);
       }else{
       JOptionPane.showMessageDialog(null, "Archivo vacío");
       }            
    }//GEN-LAST:event_botonIdenCorrectoActionPerformed

    private void botonTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablaActionPerformed
       if(aux1!=null){
       VentanaTablaSimbolos ven = new VentanaTablaSimbolos();
       ven.setVisible(true);
       }else{
       JOptionPane.showMessageDialog(null, "Primero separe los elementos del archivo");
       } 
    }//GEN-LAST:event_botonTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaArchivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonI;
    private javax.swing.JButton BotonRegresa;
    private javax.swing.JButton BotonSepara;
    private javax.swing.JButton botonIdenCorrecto;
    private javax.swing.JButton botonIdentifica;
    private javax.swing.JButton botonTabla;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTextArea1;
    // End of variables declaration//GEN-END:variables
}
